#services:
#  app:
#    image: openjdk:17-jdk-slim
#    container_name: spit-api
#    ports:
#      - "8080:8080"
#    volumes:
#      - ./target:/Spit.API
#    working_dir: /Spit.API
#    command: [ "java", "-jar", "Spit.API-0.0.1-SNAPSHOT.jar" ]
version: '3'
services:
  frontend:
    build:
      context: ./spit-api-web
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # Map React's development server port
    volumes:
      - ./spit-api-web:/app
    stdin_open: true
    tty: true
  app:
    image: openjdk:17-jdk-slim
    container_name: spit-api-react
    ports:
      - "8080:8080"
    volumes:
      - ./target:/app
    working_dir: /app
    command: [ "java", "-jar", "Spit.API-0.0.1-SNAPSHOT.jar" ]


