version: '3'
services:
  mysql:
    image: mysql
    container_name: spit-db
    environment:
      MYSQL_ROOT_PASSWORD: database
      MYSQL_DATABASE: spit-api
    ports:
      - "3306:3306"
  app:
    image: openjdk:17-jdk-slim
    container_name: spit-api
    ports:
      - "8080:8080"
    volumes:
      - ./target:/Spit.API
    working_dir: /Spit.API
    command: [ "java", "-jar", "Spit.API-0.0.1-SNAPSHOT.jar" ]
